import type { Metadata } from "next";
import { Header } from '../componetes/Header/Topo'
import {Montserrat} from 'next/font/google'
import './globals.css'
const yearCurrent = new Date().getFullYear(); 

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"]
})
export const metadata: Metadata = {
  title: `IEEE IES SYP ${yearCurrent}`, 
  description: "Generated by",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={montserrat.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
