import './globals.css'
import type { Metadata } from "next";
import { Header } from '../componetes/Header/Topo'
import img from "../assets/logos/ies_syp_logo1.png";
const yearCurrent = new Date().getFullYear(); 

export const metadata: Metadata = {
  title: `IEEE IES SYP ${yearCurrent}`,
  description: "Generated by",
  icons: {
    icon: img.src
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
