import './globals.css'
import type { Metadata } from "next";
import favicon from "../assets/imagens/logos/ies_syp_logo1.png"
import Header from '@/componetes/Header/Header';

export const metadata: Metadata = {
  title: `IEEE IES SYP`,
  description: "Generated by",
  icons: {
    icon: favicon.src
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
